config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get     '/sign_up',       to: 'users#new'
  post    '/sign_up',       to: 'users#create'
  post    '/login',         to: 'sessions#create'
  get     '/login',         to: 'sessions#new'
  delete  '/logout',        to: 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #move to constants or to a private method.

  validates :firstname,  presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { minimum: 6 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  #has_secure_password method create virtual pwd, pwd confirmation, incrypte it, and includes a presence validation,
  #but unfortunately it only applies to records with empty passwords,
  #which allows users to create invalid passwords like that with spaces. this validation adds an extra layer of validation
  validates :password, presence: true, length: { minimum: 6 }

    # Activates an account.
    def activate
      update_attribute(:activated, true)
      update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
      UserMailer.account_activation(self).deliver_now
    end

    # Sets the password reset attributes.
    def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

      # Returns true if a password reset has expired.
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end

    # Returns true if the given token matches the digest/ its encrypted version.
    def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
    end

  private

  # convert email to all lower-case
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    # Create the token and digest.
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to login_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to login_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        #log the user in and redirect to user show page
        log_in user
        redirect_to user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to login_url
      end
    else
      #user not authorize  - show error msg.
      flash.now[:danger] = 'Invalid email/password combination!'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [ :index, :edit, :update, :show ]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [ :destroy, :index ]

  def index
     @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email

      # UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account."
      redirect_to login_path
      # log_in @user
      #handle a succesful save
      # flash.now[:success]= "Welcome to CreditApp!"
      # redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      #handle a succesful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    User.find(params[:id]).destroy
    flash[:success] = "#{@user.firstname} is deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  #confirm the correct user
  def correct_user
    @user = User.find(params[:id])
    redirect_to login_url unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to login_url unless current_user.admin?
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #Logs in the given user.
  #Temporarly cookies created using session are automatically encrypted.
  #Different from persistent sessions created using cookies methods.
  #Permenant cookies are vulnerable to sessions hijacking attacks.
  def log_in(user)
    session[:user_id] = user.id
  end

  #Instance variable, which hits the database the first time
  #but returns the instance variable immediately on subsequent invocations
  #return the current logged_in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  #return true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class= "navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
    <%= link_to "sample KinApp", '/', id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item mr-2"><%= link_to "Home", "/" %></li>
        <li class="nav-item mr-2"><%= link_to "Help", "/" %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li class="nav-item mr-2"><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="nav-item mr-2 dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li class="nav-item mr-2">
          <% if current_user %>
            Hi, <%= current_user.firstname %>!
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KinApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <% flash.each do |message_type, message|%>
      <ul>
        <div class="alert alert-<%= message_type %>">
          <li><%= message %></li></br>
        </div>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error-explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, 'error') %>.
    </div>
  </div>
  <ul>
    <%= @user.errors.full_messages.each do |msg| %>
      <%
=begin%>
 <li><%= msg %></li>
<%
=end%>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="form_group">
    <%= f.label :firstname %></br>
    <%= f.text_field :firstname, class: "form_control" %>
  </div>

  <div class="form_group">
    <%= f.label :lastname %></br>
    <%= f.text_field :lastname, class: "form_control" %>
  </div>

  <div class="form_group">
    <%= f.label :email %></br>
    <%= f.email_field :email, class: "form_control" %>
  </div>

  <div class="form_group">
    <%= f.label :password %></br>
    <%= f.password_field :password, class: "form_control" %>
  </div>

  <div class="form_group">
    <%= f.label :password_confirmation, "confirm" %></br>
    <%= f.password_field :password_confirmation, class: "form_control" %></br>
  </div>

  <div class="actions mt-2">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
  <% end %>

app/views/users/edit.html.erb
<h1 class="col-12 mt-4 mx-auto text-center">Update Your profile</h1>
<div class="row">
  <div class="col-md-6 mx-auto" >
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container col-12">
  <h2 class="text-center mt-2">All Users</h2>
  <ul class="col-6 mx-auto">
    <% @user.each do |user| %>
      <li><%= user.firstname %> | <%= user.email %> |
          <%=  link_to 'delete', user, method: :delete,
                                       data: { confirm: "Are you sure?" } %>
      </li></br>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<h1 class="col-12 mt-4 mx-auto text-center">Sign up Form</h1>
<div class="row">
  <div class="col-md-6 mx-auto" >
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<h3 class="text-center"> Welcome to KinApp, <%= @user.firstname %>!</h3>